### ISSUE TITLE
ExtractChar or merged-characters-segmentation

### ISSUE THREAD

**Issue by bernd5** [livezingy/merged-characters-segmentation#3]
Hi livezingy,
I found your project here on github, tried it out - and it seems to work.
My question is: which of your projects is the best for connected characters "ExtractChar" or "merged-characters-segmentation"?
Currently I need english characters only.
 
Do you have a compiled version of "ExtractChar"?

kind regards,

Bernd

**Comment by livezingy** [comment]
Hello,
Sorry for late answer.
1.  "merged-characters-segmentation" is better for connected characters. The "ExtractChar" is detecting character from natural scene and it isn't suit for  connected characters.
2.  if you need the  compiled version of "ExtractChar", I could compiled it for you. Please give me your email.
Best wishes
livezingy
